* Not Actively Maintained




* Description

Clojure web admin (CWA) is a clojure(script)-based, metadata-driven web admin system providing some generic features in web admin system. 

The core features are as follows:

 + RESTful api&doc based on [[https://github.com/metosin/compojure-api][Computer-api&swagger]]  
 + CRUD with data-level permissions based on [[https://github.com/korma/Korma][korma]] 
 + Menu tree&toolbar with button-level permissions based on [[https://github.com/reagent-project/reagent][reagent]] & [[https://github.com/Day8/re-frame][re-frame]]
 + High-level abstract field types based on [[https://github.com/reagent-project/reagent-forms][reagent-forms]] (e.g. image, attachment, enum, select, etc.) 
 + Font-end&back-end validation based on [[https://github.com/leonardoborges/bouncer][bouncer]]


Other features:

 + Login/Logout
 + Optimistic lock for updating data
 + Default value showing in forms
 + Export as excel file & import from excel file
 + Bar chart for datagrid based on [[http://canvasjs.com/  ][CanvasJs]]

 More features are coming up..

* Quick Start

This project already has some build-in moduals including 'User', 'Role', 'Organization', which can be used
as common moduals in your new project. 
'Computer' and 'Brand' moduals are only  for demostration.

Let`s get start!


+ Clone the project

  #+BEGIN_SRC 
    git clone https://github.com/b1412/clojure-web-admin.git
  #+END_SRC

  #+BEGIN_SRC shell
    cd clojure-web-admin
  #+END_SRC

+ Execute SQL script in MySql

  #+BEGIN_SRC shell
   mysql -uroot -proot
   
   mysql> source db/demo.sql;
  #+END_SRC
   
+ Start project

Open a terminal and type lein repl to start a Clojure REPL (interactive prompt).

In the REPL, type

#+BEGIN_SRC clojure
  (start-server)
  (browser-repl)
#+END_SRC

+ Visit http://localhost:3000 and log in as admin 
   
    username: admin  
    
    password: admin

+ Go [[https://github.com/b1412/clojure-web-admin/wiki/Demo-in-details][demo in details]] to see snapshots and descriptions of core features in demo moduals before you play it.

* More details

  Go [[https://github.com/b1412/clojure-web-admin/wiki/Home][wiki]] to go deeper into the project. 

* License

Copyright © 2015 [[http://blog.kidzhou.me][Leon Zhou]]

Distributed under the Eclipse Public License, the same as Clojure.
