
* Description

Clojure web admin is a clojure(script)-based, metadata-driven web admin system,which includes basic features in
web admin system.The core features are as follows:

 + Login/Logout
 + CURD with authorities (based on korma)
 + optimistic lock
 + Menu tree with authorities
 + File upload
 + Defaul value for data when creating
 + font-end validation
 + back-end validation

* Quick Start

This project already has some build-in moduals including User, Role, Organization, which can be used
as common moduals in your new project and computer, brand moduals ,which are only for demostration.
Let`s get start!


+ Import sql script to your mysql database

    clojure-web-admin/db/demo.sql
   
+ Start front-end
 
    #+BEGIN_SRC clojure
      lein figwheel
    #+END_SRC

+ Start back-end

    #+BEGIN_SRC clojure
      lein run
    #+END_SRC
  
+ Visit http://localhost:3000/ and log in as system administrator 
   
    (username: admin  password: admin)

+ Go [[https://github.com/b1412/clojure-web-admin/wiki/Demo-in-details][demo in details]] ,to see snapshots of core features in demo moduals.

## Metadata

## Form

## Permission system

## Validation

## Add new entity

# License

Copyright © 2015 Leon Zhou

Distributed under the Eclipse Public License, the same as Clojure.
